### ISSUE TITLE
Support update or query configuration of the EaseMesh controller via emctl

### ISSUE THREAD

**Issue by zhao-kun** [megaease/easemesh#65]
### Usage
Using the following command to update the configuration of the EaseMesh controller,
```bash
emectl apply -f mesh-controller.yaml
```
Using the following command to query the configuration of the EaseMesh controller,
```bash
emctl get mesh-controller <name> [-o yaml/json] #mesh controller has and only has one, the name value can be omitted.
```
Needn't support delete/create command.

### Specification
```yaml
apiVersion: mesh.megaease.com/v1alpha1
kind: MeshController
metadata:
  name: mesh-controller # mesh controller has and only has one, the name value can be omitted.
spec:
  heartbeatInterval: 5s
  ingressPort: 19527
  kind: MeshController
  name: easemesh-controller
  registryType: consul
```
